version: '3'

services:
  test-application-server:
    build:
      context: .
      dockerfile: docker_images/test_application_server/Dockerfile
    env_file:
      - env_var
    restart: on-failure
    cmd: ["python3", "/test_application_server/tas_application_server_main.py"]
